### ISSUE TITLE
Quarnation

### ISSUE THREAD

**Issue by celikemir** [inertialsense/inertial-sense-ros#53]
Hi @siddirp 

I try to use uINS with ROS I updated the device v1.8.2. After a successful connection, I try to get quarnation and Roll Pitch Yaw values to get them I used `rostopic echo /imu` but it only returns acc x,y,z and gyro x,y,z.

**Comment by siddirp** [comment]
@celikemir,
You'll want to make sure /ins message is enabled and subscribe to that message instead of imu messages.

**Comment by celikemir** [comment]
@siddirp 
For sure, after run `rosrun inertial_sense inertial_sense_node` /ins and /imu topics seem to enabled. But `rostopic echo /ins` returns nothing on the other hand `rostopic echo /imu` returns  below data

```
 seq: 942
  stamp: 
    secs: 1606400183
    nsecs: 763668299
  frame_id: "imu"
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.00459002144635
  y: 0.024764213711
  z: 0.0142630916089
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: -5.51469612122
  y: 0.200182154775
  z: -8.04611778259
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

```

Which is include only 6-DOF information. I also test it with test.launch after modification `stream_INS: true,` still same issue there is no ins data.
